server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_services
    username: root
    password: yash1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


