server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usermicroservice
    username: root
    password: yash1234
  application:
    name: USER-SERVICE


  jpa:
    hibernate:

      ddl-auto: update
    show-sql: true
eureka:
  instance:
    ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true


